name: Full Pipeline

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files
        run: ls -la

      - name: Build Docker image
        run: docker build -t zeno-app .

      - name: Show Docker images
        run: docker images

      - name: Done
        run: echo "✅ Build complete!"
